# Copyright (C) Markus Franz Xaver Johannes Oberhumer
# CC CompilationCheck: test llvm-mingw

# see https://github.com/mstorsjo/llvm-mingw

name: 'Weekly CI CC - llvm-mingw'
on:
  schedule: [cron: '30 2 * * 3'] # run weekly Wednesday 02:30 UTC
  workflow_dispatch:
defaults: { run: { shell: bash } }
env:
  CMAKE_REQUIRED_QUIET: 'OFF'
  CMAKE_VERBOSE_MAKEFILE: 'ON'
  CTEST_OUTPUT_ON_FAILURE: 'ON'
  DEBIAN_FRONTEND: noninteractive
  UPX_CMAKE_CONFIG_FLAGS: -Wdev --warn-uninitialized
  UPX_DEBUG_TEST_FLOAT_DIVISION_BY_ZERO: 1
  UPX_DEBUG_TEST_LIBC_QSORT: 1
  ZSTD_CLEVEL: 17

jobs:
  job-llvm-mingw: # uses cmake + make
    if: github.repository_owner == 'upx'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: llvm-mingw-20230614-msvcrt
            llvm_version: 16.0.6
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20230614/llvm-mingw-20230614-msvcrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20230614-ucrt
            llvm_version: 16.0.6
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20230614/llvm-mingw-20230614-ucrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20231128-msvcrt
            llvm_version: 17.0.6
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-msvcrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20231128-ucrt
            llvm_version: 17.0.6
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20231128/llvm-mingw-20231128-ucrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20240619-msvcrt
            llvm_version: 18.1.8
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-msvcrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20240619-ucrt
            llvm_version: 18.1.8
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-ucrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20250114-msvcrt
            llvm_version: 19.1.7
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20250114/llvm-mingw-20250114-msvcrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20250114-ucrt
            llvm_version: 19.1.7
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20250114/llvm-mingw-20250114-ucrt-ubuntu-20.04-x86_64.tar.xz'
          - name: llvm-mingw-20250709-msvcrt
            llvm_version: 20.1.8
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-msvcrt-ubuntu-22.04-x86_64.tar.xz'
          - name: llvm-mingw-20250709-ucrt
            llvm_version: 20.1.8
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20250709/llvm-mingw-20250709-ucrt-ubuntu-22.04-x86_64.tar.xz'
          - name: llvm-mingw-20251216-msvcrt
            llvm_version: 21.1.8
            use_arm64ec: true
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20251216/llvm-mingw-20251216-msvcrt-ubuntu-22.04-x86_64.tar.xz'
          - name: llvm-mingw-20251216-ucrt
            llvm_version: 21.1.8
            use_arm64ec: true
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20251216/llvm-mingw-20251216-ucrt-ubuntu-22.04-x86_64.tar.xz'
          - name: llvm-mingw-20260210-msvcrt
            llvm_version: 22.1.0rc3
            use_arm64ec: true
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20260210/llvm-mingw-20260210-msvcrt-ubuntu-22.04-x86_64.tar.xz'
          - name: llvm-mingw-20260210-ucrt
            llvm_version: 22.1.0rc3
            use_arm64ec: true
            url: 'https://github.com/mstorsjo/llvm-mingw/releases/download/20260210/llvm-mingw-20260210-ucrt-ubuntu-22.04-x86_64.tar.xz'
    name: ${{ format('{0} {1}', matrix.name, matrix.llvm_version) }}
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    env:
      CMAKE_SYSTEM_NAME: Windows
      xflags: -D_WIN32_WINNT=0x0601
    steps:
      - name: Install packages
        run: |
          dpkg --add-architecture i386
          apt-get update && apt-get upgrade -y
          apt-get install -y --no-install-recommends bash ca-certificates cmake curl file git make parallel tar time util-linux wine wine32:i386 wine64 xz-utils zstd
          git config --global --add safe.directory '*' # needed when running in a container
          ls -l /usr/bin/wine*
          mkdir -p -v ~/.wine
          wineboot --init
      - name: 'Check out code'
        uses: actions/checkout@v6
        with: { submodules: true }
      - name: Check out test suite
        run: git clone --depth=1 https://github.com/upx/upx-testsuite ../deps/upx-testsuite
      - name: ${{ format('Install {0} {1}', matrix.name, matrix.llvm_version) }}
        run: |
          mkdir -p -v ~/.local/bin
          cd ~/.local/bin
          curl -sS -L -O '${{ matrix.url }}'
          ls -l ./llvm-mingw*.tar.*
          tar -xoaf ./llvm-mingw*.tar.*
          rm ./llvm-mingw*.tar.*
          # update PATH
          cd ./llvm-mingw*/bin
          echo "PATH=$PWD:$PATH" >> $GITHUB_ENV

      - name: 'Build clang aarch64'
        run: |
          export CC="aarch64-w64-mingw32-clang $xflags" CXX="aarch64-w64-mingw32-clang++ $xflags"
          make UPX_XTARGET=llvm-mingw/aarch64-w64-mingw32-clang xtarget/all
      - name: 'Build clang aarch64 static'
        run: |
          export CC="aarch64-w64-mingw32-clang -static $xflags" CXX="aarch64-w64-mingw32-clang++ -static $xflags"
          make UPX_XTARGET=llvm-mingw/aarch64-w64-mingw32-clang-static xtarget/all

      - name: 'Build clang arm64ec'
        if: ${{ matrix.use_arm64ec }}
        run: |
          export CC="arm64ec-w64-mingw32-clang $xflags" CXX="arm64ec-w64-mingw32-clang++ $xflags"
          export UPX_CONFIG_DISABLE_SAVE_TEMPS=ON
          make UPX_XTARGET=llvm-mingw/arm64ec-w64-mingw32-clang xtarget/all
      - name: 'Build clang arm64ec static'
        if: ${{ matrix.use_arm64ec }}
        run: |
          export CC="arm64ec-w64-mingw32-clang -static $xflags" CXX="arm64ec-w64-mingw32-clang++ -static $xflags"
          export UPX_CONFIG_DISABLE_SAVE_TEMPS=ON
          make UPX_XTARGET=llvm-mingw/arm64ec-w64-mingw32-clang-static xtarget/all

      - name: 'Build clang armv7'
        run: |
          export CC="armv7-w64-mingw32-clang $xflags" CXX="armv7-w64-mingw32-clang++ $xflags"
          make UPX_XTARGET=llvm-mingw/armv7-w64-mingw32-clang xtarget/all
      - name: 'Build clang armv7 static'
        run: |
          export CC="armv7-w64-mingw32-clang -static $xflags" CXX="armv7-w64-mingw32-clang++ -static $xflags"
          make UPX_XTARGET=llvm-mingw/armv7-w64-mingw32-clang-static xtarget/all

      - name: 'Build clang i686'
        run: |
          export CC="i686-w64-mingw32-clang $xflags" CXX="i686-w64-mingw32-clang++ $xflags"
          export CMAKE_CROSSCOMPILING_EMULATOR=wine
          export UPX_CONFIG_DISABLE_RUN_PACKED_TEST=ON # TODO FIXME: UPX problem
          make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang xtarget/all
      - name: 'Build clang i686 static'
        run: |
          export CC="i686-w64-mingw32-clang -static $xflags" CXX="i686-w64-mingw32-clang++ -static $xflags"
          export CMAKE_CROSSCOMPILING_EMULATOR=wine
          export UPX_CONFIG_DISABLE_RUN_PACKED_TEST=ON # TODO FIXME: UPX problem
          make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang-static xtarget/all

      - name: 'Build clang x86_64'
        run: |
          export CC="x86_64-w64-mingw32-clang $xflags" CXX="x86_64-w64-mingw32-clang++ $xflags"
          export CMAKE_CROSSCOMPILING_EMULATOR=wine
          make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang xtarget/all
      - name: 'Build clang x86_64 static'
        run: |
          export CC="x86_64-w64-mingw32-clang -static $xflags" CXX="x86_64-w64-mingw32-clang++ -static $xflags"
          export CMAKE_CROSSCOMPILING_EMULATOR=wine
          make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang-static xtarget/all

      - name: 'Make artifact'
        run: |
          ls -l build/*/*/*/upx.exe
          file  build/*/*/*/upx.exe || true
          size  build/*/*/*/upx.exe || true
          N=$(echo "upx-${GITHUB_REF_NAME}-${GITHUB_SHA:0:7}-weekly-ci-${{ matrix.name }}-${{ matrix.llvm_version }}" | sed 's/[^0-9a-zA-Z_.-]/-/g')
          mkdir -p "tmp/artifact/$N"
          for f in build/*/*/*/upx.exe; do
            d="${f%/*}" # dirname
            DESTDIR="$PWD/tmp/artifact/$N/InstallWithCMake/InstallWithDestdir/$d"         cmake --install $d
            DESTDIR="$PWD/tmp/artifact/$N/InstallWithCMake/InstallWithDestdir/$d"         cmake --install $d --prefix /temp/local/upx
            DESTDIR="$PWD/tmp/artifact/$N/InstallWithCMake/InstallWithDestdirAndStrip/$d" cmake --install $d --strip
            DESTDIR="$PWD/tmp/artifact/$N/InstallWithCMake/InstallWithDestdirAndStrip/$d" cmake --install $d --strip --prefix /temp/local/upx
            cmake --install $d --prefix "$PWD/tmp/artifact/$N/InstallWithCMake/InstallWithPrefix/$d"
            cmake --install $d --prefix "$PWD/tmp/artifact/$N/InstallWithCMake/InstallWithPrefixAndStrip/$d" --strip
          done
          (cd build && cp -v -ai --parents */*/*/upx.exe "../tmp/artifact/$N")
          (cd build && shopt -s globstar && cp -v -ai --parents **/dt_cxxlib.* "../tmp/artifact/$N")
          if command -v hardlink >/dev/null; then (cd "tmp/artifact/$N" && hardlink .) fi
          (cd tmp/artifact && tar --sort=name --zstd -cf "$N.tar.zst" "$N" && rm -rf "./$N" && ls -la && zstd -tq "$N.tar.zst")
          echo "artifact_name=$N" >> $GITHUB_ENV
      - name: ${{ format('Upload artifact {0}', env.artifact_name) }}
        uses: actions/upload-artifact@v7
        with: { name: '${{ env.artifact_name }}', path: tmp/artifact }

      - name: 'Run ctest tests i686 static with Wine'
        run: |
          make UPX_XTARGET=llvm-mingw/i686-w64-mingw32-clang-static xtarget/all+test
          ls -ld ./build/*/*/*/XTesting/*/* || true
          rm -rf ./build/*/*/*/XTesting/*/*
      - name: 'Run ctest tests x86_64 static with Wine'
        run: |
          make UPX_XTARGET=llvm-mingw/x86_64-w64-mingw32-clang-static xtarget/all+test
          ls -ld ./build/*/*/*/XTesting/*/* || true
          rm -rf ./build/*/*/*/XTesting/*/*

      - name: 'Run test suite under Wine'
        if: false
        run: |
          export upx_exe_runner=wine
          export upx_exe=./upx.exe
          export upx_testsuite_SRCDIR="$(readlink -en ../deps/upx-testsuite)"
          jobs="i686-w64-mingw32-clang-static/debug i686-w64-mingw32-clang-static/release"
          jobs="$jobs x86_64-w64-mingw32-clang-static/debug x86_64-w64-mingw32-clang-static/release"
          echo "===== parallel jobs: $jobs"
          parallel -kv --lb 'cd build/llvm-mingw/{} && bash ../../../../misc/testsuite/upx_testsuite_1.sh' ::: $jobs
          ls -ld ./build/*/*/*/tmp-upx-testsuite* || true
          rm -rf ./build/*/*/*/tmp-upx-testsuite*
